version: '3.3'

services:
  be_nba:
    image: omertopal/be_nba:1.1
    container_name: be_nba
    ports:
      - 8084:8084
    depends_on:
      - nbamysql
  nbamysql:
    image: mysql:8.0
    container_name: nbamysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nba
      - MYSQL_PASSWORD=root
    user: root
    ports:
      - 3307:3306
    volumes:
      - nbaMysqlVol:/var/lib/docker/volumes/nbamysql
  nba_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nba_phpmyadmin
    environment: 
        PMA_HOST: nbamysql
    user: root
    ports:
      - 2382:80
volumes:
  nbaMysqlVol: