
server:
  port: 8084
  servlet:
   context-path: /nba

spring:
  datasource:
    url: "jdbc:mysql://mysql:3306/nba?useSSL=false"
    username: root
    password: root    
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    data: classpath:permutations2.sql
    data: classpath:players_teams_schedule.sql, classpath:permutations1.sql, classpath:permutations2.sql
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    serialization:
      fail-on-empty-beans: false